"strict";
const bodyEl = document.getElementById("card_body");
const containerEl = document.getElementById("card_container");
const leftToggleEl = document.querySelector(".feather-toggle-left");
const rightToggleEl = document.querySelector(".feather-toggle-right");
const webLinkEl = document.querySelector(".web_link");
const contactEmailEl = document.querySelector(".contact_email");
const emailLinkEl = document.querySelector(".email_link");
// console.log(rightToggleEl, leftToggleEl);
leftToggleEl.addEventListener("click", function () {
  containerEl.style.backgroundColor = "#f5f5f5";
  containerEl.style.color = "#2c3e50";
  webLinkEl.style.color = "#2c3e50";
  leftToggleEl.style.stroke = "#2c3e50";
  leftToggleEl.style.fill = "#f5f5f5";
  rightToggleEl.style.fill = "#2c3e50";
  rightToggleEl.style.stroke = "#f5f5f5";
  contactEmailEl.style.backgroundColor = "#2c3e50";
  emailLinkEl.style.color = "#f5f5f5";
  bodyEl.style.backgroundColor = "#f5f5f5";
  containerEl.style.boxShadow = ".1px .1px 2px rgba(0, 0, 0, 0.5)";
});
rightToggleEl.addEventListener("click", function () {
  bodyEl.style.backgroundColor = "#2c3e50";
  containerEl.style.backgroundColor = "#2c3e50";
  containerEl.style.color = "#f5f5f5";
  webLinkEl.style.color = "#f5f5f5";
  rightToggleEl.style.fill = "#2c3e50";
  rightToggleEl.style.stroke = "#f5f5f5";
  leftToggleEl.style.fill = "#f5f5f5";
  leftToggleEl.style.stroke = "#2c3e50";
  contactEmailEl.style.backgroundColor = "#f5f5f5";
  emailLinkEl.style.color = "#2c3e50";
  containerEl.style.boxShadow = ".1px .1px 2px #fff";
});
